### ISSUE TITLE
Error on migrate

### ISSUE THREAD

**Issue by clairton** [visagio/redmine_file_custom_field#1]
Hello @victorlcampos .

I have updated to lastest sources and I have error when run 'rake db:migrate_plugins':

```ruby
rake aborted!
SyntaxError: /usr/local/rvm/gems/ruby-1.9.3-p551/gems/ddr-antivirus-2.1.1/lib/ddr/antivirus/scan_result.rb:9: syntax error, unexpected tLABEL
    def initialize(file_path, output, scanned_at: nil, version: nil)
                                                 ^
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/ddr-antivirus-2.1.1/lib/ddr/antivirus/scan_result.rb:9: Can't assign to nil
    def initialize(file_path, output, scanned_at: nil, version: nil)
                                                      ^
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/ddr-antivirus-2.1.1/lib/ddr/antivirus/scan_result.rb:35: syntax error, unexpected keyword_end, expecting $end
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/ddr-antivirus-2.1.1/lib/ddr/antivirus.rb:5:in `require_relative'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/ddr-antivirus-2.1.1/lib/ddr/antivirus.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/ddr-antivirus-2.1.1/lib/ddr-antivirus.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
```

Can you help-me?

**Comment by victorlcampos** [comment]
Hi,
it's probably a issue with  ddr-antivirus and ruby version (I only test with 2.3). I will open a branch without ddr-antivirus and I tell you.

Could you open a issue in https://github.com/duke-libraries/ddr-antivirus for they fix it?

**Comment by clairton** [comment]
Thanks, 

Created on https://github.com/duke-libraries/ddr-antivirus/issues/29
